spring.application.name=notes-rest-service

# Подключение к БД / Connection to DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Базовые URL / Basic URL
language-tool.client.base-url = http://localhost:8010