spring.application.name=notes-api

# Подключение к БД / Connection to DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create

# Базовые URL / Basic URL
language-tool.client.base-url=${LANGUAGE_TOOL_CLIENT_BASE_URL}
markdown-renderer.client.base-url=${MARKDOWN_RENDERER_CLIENT_BASE_URL}